package pg

import (
	"context"
	"database/sql"
	_ "embed"
	"fmt"
	"strings"

	"crypto/rand"
	"encoding/hex"

	"github.com/google/uuid"
	"github.com/nextlevelbuilder/goclaw/internal/store"
)

//go:embed tenant_schema.sql
var tenantSchemaSQL string

// InitTenantDB runs the tenant schema initialization on the given tenant DB.
func InitTenantDB(ctx context.Context, db *sql.DB) error {
	// Split by statement and execute each. Simple split on "\n\n" is fragile
	// for SQL with blank lines inside functions, but our generated schema uses
	// blank lines between statements consistently.
	stmts := splitSQLStatements(tenantSchemaSQL)
	for _, stmt := range stmts {
		stmt = strings.TrimSpace(stmt)
		if stmt == "" || strings.HasPrefix(stmt, "--") {
			continue
		}
		if _, err := db.ExecContext(ctx, stmt); err != nil {
			return fmt.Errorf("tenant schema init: %w", err)
		}
	}
	return nil
}

// splitSQLStatements splits a SQL file into individual statements.
// It handles simple cases; complex functions with blank lines are kept intact
// by tracking $$ delimiters.
func splitSQLStatements(sql string) []string {
	var stmts []string
	var buf strings.Builder
	inDollarQuote := false
	lines := strings.Split(sql, "\n")
	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "$$") {
			inDollarQuote = !inDollarQuote
		}
		buf.WriteString(line)
		buf.WriteString("\n")
		if !inDollarQuote && strings.HasSuffix(trimmed, ";") {
			stmts = append(stmts, buf.String())
			buf.Reset()
		}
	}
	if buf.Len() > 0 {
		stmts = append(stmts, buf.String())
	}
	return stmts
}

// ProvisionTenantDB creates a tenant database and initializes its schema.
// If dbConn is nil, auto-generates credentials from the master DSN.
func ProvisionTenantDB(ctx context.Context, masterDB *sql.DB, tenantID uuid.UUID, slug string, dbConn *store.TenantDBConnection, encryptionKey string) (*store.TenantDBConnection, error) {
	if dbConn == nil {
		var err error
		dbConn, err = autoGenerateDBConnection(masterDB, tenantID, slug)
		if err != nil {
			return nil, fmt.Errorf("auto-generate db conn: %w", err)
		}
	}

	// Ensure database exists
	if err := createDatabaseIfNotExists(ctx, masterDB, dbConn.DatabaseName); err != nil {
		return nil, fmt.Errorf("create database: %w", err)
	}

	// Validate connection to tenant DB
	tenantDB, err := OpenDB(dbConn.DSN())
	if err != nil {
		return nil, fmt.Errorf("open tenant db: %w", err)
	}
	defer tenantDB.Close()

	// Initialize schema
	if err := InitTenantDB(ctx, tenantDB); err != nil {
		return nil, fmt.Errorf("init tenant schema: %w", err)
	}

	return dbConn, nil
}

func autoGenerateDBConnection(masterDB *sql.DB, tenantID uuid.UUID, slug string) (*store.TenantDBConnection, error) {
	dbName := fmt.Sprintf("goclaw_tenant_%s_%s", slug, tenantID.String()[:8])
	password, err := randomPassword(32)
	if err != nil {
		return nil, err
	}
	return &store.TenantDBConnection{
		TenantID:     tenantID,
		Host:         "localhost",
		Port:         5432,
		DatabaseName: dbName,
		Username:     fmt.Sprintf("goclaw_%s", slug),
		Password:     password,
		SSLMode:      "require",
	}, nil
}

func randomPassword(n int) (string, error) {
	b := make([]byte, n)
	if _, err := rand.Read(b); err != nil {
		return "", err
	}
	return hex.EncodeToString(b), nil
}

func createDatabaseIfNotExists(ctx context.Context, masterDB *sql.DB, dbName string) error {
	var exists bool
	err := masterDB.QueryRowContext(ctx,
		"SELECT EXISTS(SELECT 1 FROM pg_database WHERE datname = $1)", dbName,
	).Scan(&exists)
	if err != nil {
		return err
	}
	if exists {
		return nil
	}
	// PostgreSQL doesn't support parameterized CREATE DATABASE
	// Sanitize dbName to prevent injection
	if !isValidDBName(dbName) {
		return fmt.Errorf("invalid database name: %s", dbName)
	}
	_, err = masterDB.ExecContext(ctx, fmt.Sprintf("CREATE DATABASE \"%s\"", dbName))
	return err
}

func isValidDBName(name string) bool {
	for _, r := range name {
		if !(r >= 'a' && r <= 'z') && !(r >= 'A' && r <= 'Z') && !(r >= '0' && r <= '9') && r != '_' && r != '-' {
			return false
		}
	}
	return len(name) > 0 && len(name) <= 63
}
