package pg

import (
	"context"
	"database/sql"
	_ "embed"
	"fmt"
	"net/url"
	"strings"

	"crypto/rand"
	"encoding/hex"

	"github.com/google/uuid"
	"github.com/nextlevelbuilder/goclaw/internal/store"
)

//go:embed tenant_schema.sql
var tenantSchemaSQL string

// InitTenantDB runs the tenant schema initialization on the given tenant DB.
func InitTenantDB(ctx context.Context, db *sql.DB) error {
	stmts := splitSQLStatements(tenantSchemaSQL)
	for _, stmt := range stmts {
		stmt = strings.TrimSpace(stmt)
		if stmt == "" || isOnlyCommentsOrEmpty(stmt) {
			continue
		}
		if _, err := db.ExecContext(ctx, stmt); err != nil {
			firstLine := stmt
			if idx := strings.IndexByte(firstLine, '\n'); idx > 0 {
				firstLine = firstLine[:idx]
			}
			if len(firstLine) > 120 {
				firstLine = firstLine[:120] + "..."
			}
			return fmt.Errorf("tenant schema init [stmt: %s]: %w", firstLine, err)
		}
	}
	return nil
}

func isOnlyCommentsOrEmpty(stmt string) bool {
	for _, line := range strings.Split(stmt, "\n") {
		trimmed := strings.TrimSpace(line)
		if trimmed != "" && !strings.HasPrefix(trimmed, "--") {
			return false
		}
	}
	return true
}

// splitSQLStatements splits a SQL file into individual statements.
// It handles simple cases; complex functions with blank lines are kept intact
// by tracking $$ delimiters.
func splitSQLStatements(sql string) []string {
	var stmts []string
	var buf strings.Builder
	inDollarQuote := false
	lines := strings.Split(sql, "\n")
	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		// Toggle once per $$ occurrence on the line (handles AS $$, $$ LANGUAGE,
		// END $$;, and one-line $$...$$ blocks correctly).
		for i := 0; i < strings.Count(trimmed, "$$"); i++ {
			inDollarQuote = !inDollarQuote
		}
		buf.WriteString(line)
		buf.WriteString("\n")
		if !inDollarQuote && strings.HasSuffix(trimmed, ";") {
			stmts = append(stmts, buf.String())
			buf.Reset()
		}
	}
	if buf.Len() > 0 {
		stmts = append(stmts, buf.String())
	}
	return stmts
}

// ProvisionTenantDB creates a tenant database and initializes its schema.
// If dbConn is nil, auto-generates credentials from the master DSN.
// masterDSN is used to open a superuser connection to the tenant DB for schema init.
func ProvisionTenantDB(ctx context.Context, masterDB *sql.DB, tenantID uuid.UUID, slug string, dbConn *store.TenantDBConnection, encryptionKey string, defaultSSLMode string, masterDSN string) (*store.TenantDBConnection, error) {
	if dbConn == nil {
		var err error
		dbConn, err = autoGenerateDBConnection(masterDB, tenantID, slug, defaultSSLMode)
		if err != nil {
			return nil, fmt.Errorf("auto-generate db conn: %w", err)
		}
	}

	// Ensure user exists with correct password
	if err := createOrUpdateUser(ctx, masterDB, dbConn.Username, dbConn.Password); err != nil {
		return nil, fmt.Errorf("create user: %w", err)
	}

	// Ensure database exists
	if err := createDatabaseIfNotExists(ctx, masterDB, dbConn.DatabaseName); err != nil {
		return nil, fmt.Errorf("create database: %w", err)
	}

	// Make tenant user the database owner for isolation
	if err := setDatabaseOwner(ctx, masterDB, dbConn.DatabaseName, dbConn.Username); err != nil {
		return nil, fmt.Errorf("set database owner: %w", err)
	}

	// Initialize schema as master (extensions like vector require superuser)
	masterTenantDSN := replaceDBNameInDSN(masterDSN, dbConn.DatabaseName)
	masterTenantDB, err := OpenDB(masterTenantDSN)
	if err != nil {
		return nil, fmt.Errorf("open tenant db as master: %w", err)
	}
	defer masterTenantDB.Close()

	if err := InitTenantDB(ctx, masterTenantDB); err != nil {
		return nil, fmt.Errorf("init tenant schema: %w", err)
	}

	if err := grantTenantPrivileges(ctx, masterTenantDB, dbConn.Username); err != nil {
		return nil, fmt.Errorf("grant tenant privileges: %w", err)
	}

	// Verify tenant user can connect
	tenantDB, err := OpenDB(dbConn.DSN())
	if err != nil {
		return nil, fmt.Errorf("open tenant db: %w", err)
	}
	defer tenantDB.Close()

	return dbConn, nil
}

func autoGenerateDBConnection(masterDB *sql.DB, tenantID uuid.UUID, slug string, defaultSSLMode string) (*store.TenantDBConnection, error) {
	dbName := fmt.Sprintf("goclaw_tenant_%s_%s", slug, tenantID.String()[:8])
	password, err := randomPassword(32)
	if err != nil {
		return nil, err
	}
	sslMode := defaultSSLMode
	if sslMode == "" {
		sslMode = "prefer"
	}
	return &store.TenantDBConnection{
		TenantID:     tenantID,
		Host:         "localhost",
		Port:         5432,
		DatabaseName: dbName,
		Username:     fmt.Sprintf("goclaw_%s", slug),
		Password:     password,
		SSLMode:      sslMode,
	}, nil
}

func randomPassword(n int) (string, error) {
	b := make([]byte, n)
	if _, err := rand.Read(b); err != nil {
		return "", err
	}
	return hex.EncodeToString(b), nil
}

func createOrUpdateUser(ctx context.Context, masterDB *sql.DB, username, password string) error {
	var exists bool
	err := masterDB.QueryRowContext(ctx,
		"SELECT EXISTS(SELECT 1 FROM pg_roles WHERE rolname = $1)", username,
	).Scan(&exists)
	if err != nil {
		return err
	}
	if !isValidDBName(username) {
		return fmt.Errorf("invalid username: %s", username)
	}
	// Password is hex-encoded random bytes (0-9a-f) — safe for single-quote literal,
	// but defensively escape anyway.
	safePass := strings.ReplaceAll(password, "'", "''")
	if exists {
		_, err = masterDB.ExecContext(ctx, fmt.Sprintf("ALTER ROLE \"%s\" WITH LOGIN PASSWORD '%s'", username, safePass))
	} else {
		_, err = masterDB.ExecContext(ctx, fmt.Sprintf("CREATE ROLE \"%s\" WITH LOGIN PASSWORD '%s'", username, safePass))
	}
	return err
}

func setDatabaseOwner(ctx context.Context, masterDB *sql.DB, dbName, username string) error {
	if !isValidDBName(dbName) {
		return fmt.Errorf("invalid database name: %s", dbName)
	}
	if !isValidDBName(username) {
		return fmt.Errorf("invalid username: %s", username)
	}
	_, err := masterDB.ExecContext(ctx, fmt.Sprintf("ALTER DATABASE \"%s\" OWNER TO \"%s\"", dbName, username))
	return err
}

func createDatabaseIfNotExists(ctx context.Context, masterDB *sql.DB, dbName string) error {
	var exists bool
	err := masterDB.QueryRowContext(ctx,
		"SELECT EXISTS(SELECT 1 FROM pg_database WHERE datname = $1)", dbName,
	).Scan(&exists)
	if err != nil {
		return err
	}
	if exists {
		return nil
	}
	// PostgreSQL doesn't support parameterized CREATE DATABASE
	// Sanitize dbName to prevent injection
	if !isValidDBName(dbName) {
		return fmt.Errorf("invalid database name: %s", dbName)
	}
	_, err = masterDB.ExecContext(ctx, fmt.Sprintf("CREATE DATABASE \"%s\"", dbName))
	return err
}

func isValidDBName(name string) bool {
	for _, r := range name {
		if !(r >= 'a' && r <= 'z') && !(r >= 'A' && r <= 'Z') && !(r >= '0' && r <= '9') && r != '_' && r != '-' {
			return false
		}
	}
	return len(name) > 0 && len(name) <= 63
}

// replaceDBNameInDSN swaps the database name in a PostgreSQL DSN (URL or key-value format).
func replaceDBNameInDSN(dsn, dbName string) string {
	if strings.HasPrefix(dsn, "postgres://") || strings.HasPrefix(dsn, "postgresql://") {
		if u, err := url.Parse(dsn); err == nil && u != nil {
			u.Path = "/" + dbName
			return u.String()
		}
	}
	parts := strings.Fields(dsn)
	for i, p := range parts {
		if strings.HasPrefix(p, "dbname=") {
			parts[i] = "dbname=" + dbName
			return strings.Join(parts, " ")
		}
	}
	return dsn + " dbname=" + dbName
}

// grantTenantPrivileges gives the tenant user full access to schema objects.
func grantTenantPrivileges(ctx context.Context, db *sql.DB, username string) error {
	if !isValidDBName(username) {
		return fmt.Errorf("invalid username: %s", username)
	}
	stmts := []string{
		fmt.Sprintf("GRANT ALL ON SCHEMA public TO \"%s\"", username),
		fmt.Sprintf("GRANT ALL ON ALL TABLES IN SCHEMA public TO \"%s\"", username),
		fmt.Sprintf("GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO \"%s\"", username),
		fmt.Sprintf("GRANT ALL ON ALL FUNCTIONS IN SCHEMA public TO \"%s\"", username),
		fmt.Sprintf("ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO \"%s\"", username),
		fmt.Sprintf("ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO \"%s\"", username),
		fmt.Sprintf("ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO \"%s\"", username),
	}
	for _, stmt := range stmts {
		if _, err := db.ExecContext(ctx, stmt); err != nil {
			return fmt.Errorf("grant privileges: %w", err)
		}
	}
	return nil
}
